### ISSUE TITLE
Javascript is recognized as expression

### ISSUE THREAD

**Issue by jechtom** [jechtom/Redwood#3]
In this rwhtml script block:

<pre>
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-33057153-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
</pre>

Expression is found:

<pre>
{
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        }
</pre>

It should not be recognized as expression (explicit rule for script block?). 

Of course there should be way how to define "literal with binding" inside JavaScript code. We will probably need some special syntax for that. For example:

<pre>
 var x = "{{Binding SomeUrl}}";
</pre>

**Comment by tomasherceg** [comment]
I don't think bindings in javascript code are necessary - there will be clean javascript way how to access viewmodel properties - perhaps something like Redwood.getViewModelFor(document.body).PropertyName()
Server-side bindings could be there however I don't like that the syntax is different in HTML and JS code for the same thing. 
Maybe it would be enough to treat everything between <script> and </script> as literal for now and look at the in-script binding syntax later.

**Comment by jechtom** [comment]
In ASP.NET MVC there are few scenarios in which I find this useful. 
For example dynamic URL resolving based on routing is better than hard coded URL addresses in some cases:

<pre>
 $.ajax({
  url: "@Url.Action("AjaxAction")",
  ...
 });
</pre>

**Comment by tomasherceg** [comment]
OK, let's introduce the {{Binding ...}} syntax in the scripts, we may change it later if we find something better.

**Comment by tomasherceg** [comment]
Implemented, test cases added.
