### ISSUE TITLE
Low-level rwhtml parser shows unexpected error "The tag was not closed."

### ISSUE THREAD

**Issue by jechtom** [jechtom/Redwood#5]
Rwhtml:

```
...
<rw:Button Text="{Binding Title} aa" />
...
```

Error:
HTTP 500 InternalServerError
Redwood.Framework.Parsing.ParserException: The tag was not closed.

Please check if this is correct behavior. I would expect some error related to attribute value not whole element. This can be hidden potential bug.

**Comment by tomasherceg** [comment]
Fixed and test case added.
